import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {SidebarProvider, Sidebar, SidebarContent} from '@/components/ui/sidebar';
import {SiteHeader} from '@/app/components/site-header';
import { SidebarNav } from '@/app/components/sidebar-nav';

import {
  Briefcase,
  Verified,
  Contact2,
  GraduationCap,
  Home,
  Lightbulb,
  User,
} from 'lucide-react';
import {Toaster} from "@/components/ui/toaster"
import HomePage from '@/app/page';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex flex-col min-h-screen">
            <SiteHeader />
            <div className="flex flex-1">
              <Sidebar collapsible="icon">
                <SidebarContent>
                  <SidebarNav
                    items={[
                      {
                        href: "#hero",
                        label: "Home",
                        icon: <Home className="h-4 w-4" />,
                      },
                      {
                        href: "#about",
                        label: "About",
                        icon: <User className="h-4 w-4" />,
                      },
                      {
                        href: "#education",
                        label: "Education",
                        icon: <GraduationCap className="h-4 w-4" />,
                      },
                      {
                        href: "#experience",
                        label: "Experience",
                        icon: <Briefcase className="h-4 w-4" />,
                      },
                      {
                        href: "#certifications",
                        label: "Certifications",
                        icon: <Verified className="h-4 w-4" />,
                      },
                      {
                        href: "#skills",
                        label: "Skills",
                        icon: <Lightbulb className="h-4 w-4" />,
                      },
                      {
                        href: "#projects",
                        label: "Projects",
                        icon: <Home className="h-4 w-4" />,
                      },
                      {
                        href: "#contact",
                        label: "Contact",
                        icon: <Contact2 className="h-4 w-4" />,
                      },
                    ]}
                  />
                </SidebarContent>
              </Sidebar>
              <main className="flex-1 bg-background">
                <div className="container mx-auto px-4 max-w-7xl">
                  <HomePage />
                </div>
              </main>
            </div>
          </div>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
